/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.ts to modify the generation of this file.




import * as BestSellersCarousel from 'src/components/BestSellersCarousel';
import * as BlogCarousel from 'src/components/BlogCarousel';
import * as CategoryCarousel from 'src/components/CategoryCarousel';
import * as ContentBlock from 'src/components/ContentBlock';
import * as DynamicCards from 'src/components/DynamicCards';
import * as FAQList from 'src/components/FAQList';
import * as FeaturedCarousel from 'src/components/FeaturedCarousel';
import * as HeroBanner from 'src/components/HeroBanner';
import * as HeroCarousel from 'src/components/HeroCarousel';
import * as KeyDetails from 'src/components/KeyDetails';
import * as RelatedCards from 'src/components/RelatedCards';
import * as RichText from 'src/components/RichText';
import * as Title from 'src/components/Title';

const components = new Map();

components.set('BestSellersCarousel', BestSellersCarousel);
components.set('BlogCarousel', BlogCarousel);
components.set('CategoryCarousel', CategoryCarousel);
components.set('ContentBlock', ContentBlock);
components.set('DynamicCards', DynamicCards);
components.set('FAQList', FAQList);
components.set('FeaturedCarousel', FeaturedCarousel);
components.set('HeroBanner', HeroBanner);
components.set('HeroCarousel', HeroCarousel);
components.set('KeyDetails', KeyDetails);
components.set('RelatedCards', RelatedCards);
components.set('RichText', RichText);
components.set('Title', Title);

// Next.js 'dynamic' import and JavaScript 'dynamic' import are different.
// Next.js 'dynamic(...)' returns common 'React.ComponentType' while
// 'import('...')' returns 'Promise' that will resolve module.
// componentModule uses 'import(...)' because primary usage of it to get not only 'React Component' (default export) but all named exports.
// See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports
// componentFactory uses 'dynamic(...)' because primary usage of it to render 'React Component' (default export).
// See https://nextjs.org/docs/advanced-features/dynamic-import
// At the end you will have single preloaded script for each lazy loading module.

export function componentModule(componentName: string) {
  const component = components.get(componentName);

  // check that component is lazy loading module
  if (!component?.default && component?.module) {
    // return js dynamic import
    return component.module();
  }

  return component;
}
  
export function componentFactory(componentName: string) {
  const component = components.get(componentName);

  // check that component should be dynamically imported
  if (component?.element) {
    // return next.js dynamic import
    return component.element();
  }

  return component?.default || component;
}
